app/models/categories.py
from .db import get_connection

mydb = get_connection()

class Category:

    def __init__(self, category, description, id=None):
        self.id = id
        self.category = category
        self.description = description

    def save(self):
        # Create a New Object in DB
        if self.id is None:
            with mydb.cursor() as cursor:
                sql = "INSERT INTO categories(category, description) VALUES(%s, %s)"
                val = (self.category, self.description)
                cursor.execute(sql, val)
                mydb.commit()
                self.id = cursor.lastrowid
                return self.id
        # Update an Object
        else:
            with mydb.cursor() as cursor:
                sql = "UPDATE categories SET category = %s, description = %s WHERE id = %s"
                val = (self.category, self.description, self.id)
                cursor.execute(sql, val)
                mydb.commit()
                return self.id
            
    def delete(self):
        with mydb.cursor() as cursor:
            sql = f"DELETE FROM categories WHERE id = { self.id }"
            cursor.execute(sql)
            mydb.commit()
            return self.id
            
    @staticmethod
    def get(id):
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT category, description FROM categories WHERE id = { id }"
            cursor.execute(sql)
            result = cursor.fetchone()
            print(result)
            category = Category(result["category"], result["description"], id)
            return category
        
    @staticmethod
    def get_all():
        categories = []
        with mydb.cursor(dictionary=True) as cursor:
            sql = f"SELECT id, category, description FROM categories"
            cursor.execute(sql)
            result = cursor.fetchall()
            for item in result:
                categories.append(Category(item["category"], item["description"], item["id"]))
            return categories
    
    @staticmethod
    def count_all():
        with mydb.cursor() as cursor:
            sql = f"SELECT COUNT(id) FROM categories"
            cursor.execute(sql)
            result = cursor.fetchone()
            return result[0]
        
    def __str__(self):
        return f"{ self.id } - { self.category }"

app/views/home_views.py
from flask import Blueprint, render_template

home_views = Blueprint('home', __name__)

@home_views.route('/')
@home_views.route('/home/')
def home():
    return render_template('home/home.html')

@home_views.route('/about/')
def about():
    return render_template('home/about.html')

@home_views.route('/contact/')
def contact():
    return render_template('home/contact.html')

app/views/user_views.py
from flask import Blueprint, render_template, redirect, url_for, flash, abort

from models.users import User

from forms.user_forms import RegisterForm, LoginForm, ProfileForm

from utils.file_handler import save_image

user_views = Blueprint('user', __name__)

@user_views.route('/users/register/', methods=('GET', 'POST'))
def register():
    form = RegisterForm()

    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        email = form.email.data

        user = User(username, password, email)
        user.save()

        return redirect(url_for('user.login'))
    return render_template('users/register.html', form=form)

@user_views.route('/users/login/', methods=('GET', 'POST'))
def login():
    form = LoginForm()

    if form.validate_on_submit():
        username = form.username.data
        password = form.password.data
        user = User.get_by_password(username, password)
        if not user:
            flash('Verifica tus Datos')
        else:
            return render_template('home/home.html', user=user)
    return render_template('users/login.html', form=form)

@user_views.route('/users/<int:id>/profile/', methods=('GET', 'POST'))
def profile(id):
    form = ProfileForm()
    user = User.__get__(id)
    if not user:
        abort(404)
    if form.validate_on_submit():
        user.first_name = form.first_name.data
        user.last_name = form.last_name.data
        f = form.image.data
        if f:
            user.image = save_image(f, 'images/profiles', user.username)
        user.save()
    form.first_name.data = user.first_name
    form.last_name.data = user.last_name
    image = user.image
    return render_template('users/profile.html', form=form, image=image)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                <li><a href="{{ url_for('home.home') }}">Home</a></li>
                <li><a href="{{ url_for('home.about') }}">About</a></li>
                <li><a href="{{ url_for('home.contact') }}">Contact</a></li>
                <li><a href="{{ url_for('category.categories') }}">Categories</a></li>
                {% if user %}
                <li><a href="#">Logout</a></li>
                {% else %}
                <li><a href="{{ url_for('user.login') }}">Login</a></li>
                <li><a href="{{ url_for('user.register') }}">Registro</a></li>
                {% endif %}
            </ul>
        </nav>
    </header>
    <section class="container">
        {% block content %}
            
        {% endblock %}
    </section>
    <footer>
        <p>Copyright @franlop24</p>
    </footer>
</body>
</html>

app/templates/categories.html
{% extends 'base.html' %}

{% block title %}
Categorias
{% endblock %}
    
{% block content %}
<h1>Categories Page</h1>
<h2>Lista de Categorias</h2>
<a href="{{ url_for('create_cat') }}" class="btn">Nueva Categoria</a>
<table id="categories">
    <thead>
        <tr>
            <th>ID</th>
            <th>Category</th>
            <th>Description</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        {% for cat in categories %}
            <tr>
                <td>{{ cat.id }}</td>
                <td>{{ cat.category }}</td>
                <td>{{ cat.description }}</td>
                <td>
                    <a href="{{ url_for('update_cat', id=cat.id) }}">
                        <i class="fa fa-refresh fa-spin"></i>
                    </a> / 
                    <a href="{{ url_for('delete_cat', id=cat.id) }}">
                        <i class="fa fa-trash"></i>
                    </a>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}
    